pla.nette.org translation/missing translated
contributte/planette-site pull request #7
Opened 2017-07-09 13:33 UTC by meridius

This added mostly already translated articles from play.nette.org, which were not yet part of the codebase.

They are located in temp directory and are missing timestamp from their filenames and from "details" tables because date on play.nette.org is not exact.   
@paveljanda could you please send me those dates?

I've also created new overview table reflecting those changes https://docs.google.com/spreadsheets/d/1e57AO2FXDKZXE5nhnMPWI2jtPaYaAQ_8hx-Z7JFm-go/edit?usp=sharing

2017-07-10 14:05 UTC, f3l1x commented
Look's good. Do you still working on that?

2017-07-11 12:03 UTC, meridius commented
Just waiting on those dates.

2017-07-15 18:56 UTC, paveljanda commented
@meridius Added dates + 2 notes :)

2017-07-15 20:49 UTC, meridius commented
@paveljanda cool! Where do I find that? 😄

2017-07-15 21:04 UTC, paveljanda commented
@meridius 
<img width="675" alt="screen shot 2017-07-15 at 23 03 47" src="https://user-images.githubusercontent.com/1488874/28242664-f288443c-69b1-11e7-9442-447d6351ec80.png">
<img width="676" alt="screen shot 2017-07-15 at 23 03 39" src="https://user-images.githubusercontent.com/1488874/28242666-f44eac5c-69b1-11e7-99f0-ce35b8cef9ae.png">

2017-07-16 09:43 UTC, paveljanda requested changes

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/connect-dibi-as-a-service-with-tracy-bar.md
> +date: ""
2014-10-28 11:27:11

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/dibi-fluent-insert.md
> +date: ""
2014-10-28 10:19:14

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/different-layout-in-administration.md
> +date: ""
2015-04-24 20:12:32

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/examples-of-macro-n-class-usage.md
> +date: ""
2014-10-28 11:36:56

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/form-image-and-rules.md
> +date: ""
2014-10-28 10:35:36

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/how-to-ajax-response-with-json.md
> +date: ""
2014-11-19 00:46:00

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/how-to-change-latte-syntax-for-javascript.md
> +date: ""
2014-10-28 11:22:57

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/how-to-setup-simpleauthenticator.md
> +date: ""
2014-11-02 11:34:40

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/how-to-test-exception-call.md
> +date: ""
2014-10-28 18:21:20

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/how-to-use-texy-in-latte-template-as-a-filter.md
> +date: ""
2015-02-01 16:59:53

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/howto-lazy-factory.md
> +slug: "howto-lazy-factory"
Maybe "ho to CREATE lazy factory"?

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/howto-lazy-factory.md
> +date: ""
2014-10-28 11:40:28

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/latte-simple-foreach-with-first-last-macro.md
> +date: ""
2014-10-28 11:23:27

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/overwrite-whole-section-in-neon-config.md
> +date: ""
2014-10-28 12:21:55

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/recursive-delete-folder.md
> +date: ""
2014-10-28 11:24:06

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/recursive-delete-folder.md
> +title: "Recursive delete folder"
RecursiveLY? :)
Or Recursive directory deleting

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/simple-way-hot-to-setup-basic-router-from-config-file.md
> +date: ""
2014-10-28 12:23:25

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/use-persistent-parameters-in-presenters.md
> +date: ""
2014-10-28 12:26:24

2017-07-16 09:43 UTC, paveljanda commented on content/oldPlanette/x/conditional-button-in-form.md
> +date: ""
2014-11-05 20:31:41

2017-07-16 09:47 UTC, f3l1x commented
@meridius We have a dates! :-) @paveljanda didn't submit his review :-D Lol!

2017-07-16 09:49 UTC, f3l1x commented
![download](https://user-images.githubusercontent.com/538058/28246546-bd8eb908-6a1c-11e7-8094-b9caeeca3c34.jpeg)

2017-07-16 20:34 UTC, meridius commented
@f3l1x any idea of what's wrong? It doesn't make sense to me.
https://travis-ci.org/planette/planette/builds/254230384#L286

Thanks

2017-07-17 06:27 UTC, f3l1x commented
@meridius 

```
ERROR 2017/07/16 20:22:37 failed to parse page metadata for "oldPlanette/2014/2014-10-28-examples-of-macro-n-class-usage.md": yaml: line 3: did not find expected key
Error: Error building site: Errors reading pages: Error: failed to parse page metadata for "oldPlanette/2014/2014-10-28-examples-of-macro-n-class-usage.md": yaml: line 3: did not find expected key for 2014-10-28-examples-of-macro-n-class-usage.md
```

2017-07-17 07:51 UTC, meridius commented on content/oldPlanette/2014/2014-10-28-examples-of-macro-n-class-usage.md
> +title: "Examples of macro "n:class" usage"
Note to self: Fix quotes within quotes.

2017-07-17 07:52 UTC, meridius commented
I was blind but now I see. 😂

2017-07-17 07:57 UTC, f3l1x commented on content/oldPlanette/2014/2014-10-28-examples-of-macro-n-class-usage.md
> +title: "Examples of macro "n:class" usage"
`"Examples of macro \"n:class\" usage"`, doesn't work?

2017-07-17 20:48 UTC, meridius commented
I think, this can be merged now.

2017-07-17 20:49 UTC, paveljanda commented
Should be the tag name `n:macro` or just `macro`? People would have to distinguish between them which can be misleading..

2017-07-17 20:54 UTC, meridius commented
Well, the snippet is for `n:class`, which is a `n:macro`. So it makes sense to me that it should have the same named tag. Naming it just `macro` could confuse readers that the article is about bracket `{macros}`.

2017-07-17 20:57 UTC, paveljanda commented
`n:macro` is just special case of `macro`, hm? :) :)
Viz https://latte.nette.org/cs/macros

2017-07-17 21:04 UTC, meridius commented
OK. So how about:

```
title: "Examples of macro \"n:class\" usage"
tags: ["snippet", "latte", "macro"]
```

2017-07-17 21:06 UTC, paveljanda commented
Love it. Thanks a lot and sorry for me being so pedantic. :D

2017-07-17 21:07 UTC, meridius commented
No problem. I'm the same way. ;)

2017-07-18 07:35 UTC, merged

2017-07-18 07:35 UTC, f3l1x commented
@meridius Big thanks! :+1: 

Also pedantic @paveljanda, you :dog2:!